version: "3.7"
services:
  node:
    container_name: game-role-attendant-app
    image: tutk0/game-role-attendant:latest
    build:
      context: .
      args:
        buildversion: 0.2

    ports:
      - "3000:3000"
    networks:
      - game-role-attendant-network
    volumes:
      - ./logs:/var/www/logs
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    container_name: redis-db
    image: redislabs/redismod:latest
    networks:
      - game-role-attendant-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  game-role-attendant-network:
    driver: bridge
