version: "3.7"
services:
  node:
    container_name: game-role-attendant-app
    image: tutk0/game-role-attendant:latest
    restart: unless-stopped
    build:
      context: .
      args:
        buildversion: 0.5

    ports:
      - "3000:3000"
    networks:
      - game-role-attendant-network
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    container_name: redis-db
    image: redislabs/redismod:latest
    restart: unless-stopped
    networks:
      - game-role-attendant-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  game-role-attendant-network:
    driver: bridge
